# DATA PROCESSING USING SCI-KIT LEARN

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataDF = pd.read_csv('pre-process_datasample.csv')

In [3]:
dataDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    9 non-null      object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [4]:
dataDF.Country.fillna(dataDF.Country.mode()[0] , inplace=True)

In [5]:
dataDF

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
dataDF.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [7]:
dataDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [8]:
#Seperate Features and Label
featuresDF = dataDF.iloc[:,:-1].values # -1 INDICATES..UPPER BOUND VALUE..end value +1
labelDF = dataDF.iloc[:,-1].values

In [9]:
featuresDF

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
labelDF

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [11]:
dataDF

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [12]:
featuresDF

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [13]:
labelDF

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
?SimpleImputer

Init signature:
SimpleImputer(
    *,
    missing_values=nan,
    strategy='mean',
    fill_value=None,
    verbose=0,
    copy=True,
    add_indicator=False,
)
Docstring:     
Imputation transformer for completing missing values.

Read more in the :ref:`User Guide <impute>`.

.. versionadded:: 0.20
   `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
   estimator which is now removed.

Parameters
----------
missing_values : int, float, str, np.nan or None, default=np.nan
    The placeholder for the missing values. All occurrences of
    `missing_values` will be imputed. For pandas' dataframes with
    nullable integer dtypes with missing values, `missing_values`
    should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.

strategy : string, default='mean'
    The imputation strategy.

    - If "mean", then replace missing values using the mean along
      each column. Can only be used with numeric data.
    - If "median", then replace missing values

In [16]:
siAge = SimpleImputer(strategy='mean' , 
                   missing_values=np.nan)

In [17]:
siSalary = SimpleImputer(strategy='median',
                        missing_values=np.nan)

In [18]:
np.nan == np.nan # always false

False

In [19]:
featuresDF[:,1]

array([44.0, 27.0, 30.0, 38.0, 40.0, 35.0, nan, 48.0, 50.0, 37.0],
      dtype=object)

In [20]:
featuresDF[:,1].ndim

1

In [21]:
# the above data is in 1-D, but sklearn expects 2-d data

In [22]:
featuresDF[:,[1]]

array([[44.0],
       [27.0],
       [30.0],
       [38.0],
       [40.0],
       [35.0],
       [nan],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [23]:
featuresDF[:,[1]].ndim

2

In [24]:
#  now it has become 2d DATA

In [25]:
siAge.fit(featuresDF[:,1]) # calculates the mean of the column

ValueError: Expected 2D array, got 1D array instead:
array=[44. 27. 30. 38. 40. 35. nan 48. 50. 37.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
siAge.fit(featuresDF[:,[1]]) # calculates the mean of the column

SimpleImputer()

In [27]:
siAge.fit(featuresDF[:,1].reshape(-1,1)) # same as above # SimpleImputer() is the default of strategy="mean"

SimpleImputer()

In [28]:
siSalary.fit(featuresDF[:,2].reshape(-1,1))

SimpleImputer(strategy='median')

In [29]:
featuresDF[:,[1]] = siAge.transform(featuresDF[:,[1]])
featuresDF[:,[2]] = siSalary.transform(featuresDF[:,[2]])

In [30]:
dataDF

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [31]:
featuresDF

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [32]:
#One Hot Encoding for categorical variables
# reshape is required because sklearn asks for 2d data
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
fCountry = ohe.fit_transform(featuresDF[:,0].reshape(-1,1)) # .reshape(row , columns)
fCountry                                      # row=-1 means till last rows, 1 means 1st column, i.e, contry

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [33]:
finalFeatures = np.concatenate((fCountry, featuresDF[:,[1,2]]) , axis = 1) # to bring all together

In [34]:
# if any doubt on axis=1, then check for 
?np.concatenate

Docstring:
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

    .. versionadded:: 1.20.0

Returns

In [35]:
finalFeatures

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
# Conclusions on processing of data
# 1. performance wise both ways i.e,Pandas and sklearn both are same
# 2. mermory for calculation also same because pandas also use numpy only
# 3. only to aware both the procedures ..we have gone thru
# 4. if organisation ahving not of pandas becuase of security standards or others
#    then sklearn way is helpful

In [ ]:
#Sparse Matrix EXample
import numpy as np
matrix1 = np.matrix([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,1,2]])
matrix1

In [ ]:
#Bytes
import sys
sys.getsizeof(matrix1)

In [ ]:
#Compress the matrix with a goal to save memory space
from scipy.sparse import csr_matrix
compressedMatrix = csr_matrix(matrix1)

In [ ]:
sys.getsizeof(compressedMatrix)